// src/components/GitHubCard.jsx
import { FaGithub } from "react-icons/fa";
import QRCode from "react-qr-code";

export default function GitHubCard({ data }) {
  return (
    <div className="w-[320px] bg-white rounded-xl shadow-lg border overflow-hidden font-sans">
      {/* Header */}
      <div className="bg-gray-900 text-white flex items-center px-4 py-2">
        <FaGithub size={20} className="mr-2" />
        <h2 className="font-bold">Github Card</h2>
      </div>

      {/* Profile Section */}
      <div className="flex flex-col items-center px-6 py-4">
        <div className="w-20 h-20 bg-gray-300 rounded-md mb-2 overflow-hidden">
          {data.avatar ? (
            <img
              src={data.avatar}
              alt="Avatar"
              className="w-full h-full object-cover"
            />
          ) : null}
        </div>
        <div className="bg-gray-800 text-white text-sm px-3 py-1 rounded-md mb-1">
          {data.fullName || "Full Name"}
        </div>
        <p className="text-gray-600 text-sm">@{data.username || "userName"}</p>
      </div>

      {/* Followers & Stars */}
      <div className="flex justify-center gap-4 text-sm px-6">
        <span>{data.followers || "2.4k"} Followers</span>
        <span>{data.stars || "4.2k"}★</span>
      </div>

      {/* Bio */}
      <div className="px-6 py-3 text-gray-700 text-sm">
        {data.bio ||
          "Hey there, I am a Github user and this is my cool github card"}
      </div>

      {/* Company */}
      <div className="px-6 text-sm text-gray-700">
        Company:{" "}
        <span className="font-semibold">
          {data.company || "Unemployed"}
        </span>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 text-center py-3 text-sm">
        <div>
          <p className="font-bold">{data.commits || "5.3k"}</p>
          <p className="text-gray-500">Commits</p>
        </div>
        <div>
          <p className="font-bold">{data.repos || "500"}</p>
          <p className="text-gray-500">Repos</p>
        </div>
        <div>
          <p className="font-bold">{data.prs || "400"}</p>
          <p className="text-gray-500">PR</p>
        </div>
        <div>
          <p className="font-bold">{data.issues || "60"}</p>
          <p className="text-gray-500">Issues</p>
        </div>
      </div>

      {/* Joined & Location */}
      <div className="flex justify-between items-start px-6 py-3 text-sm">
        <div>
          <p>
            Joined:{" "}
            <span className="font-semibold">
              {data.joined || "24/06/2016"}
            </span>
          </p>
          <p>
            Location:{" "}
            <span className="font-semibold">
              {data.location || "Mumbai"}
            </span>
          </p>
        </div>
        <QRCode
          value={data.profileUrl || "https://github.com"}
          size={60}
        />
      </div>

      {/* Skills */}
      {data.skills?.length > 0 && (
        <div className="px-6 py-3">
          <div className="flex flex-wrap gap-2">
            {data.skills.map((skill, idx) => (
              <span
                key={idx}
                className="text-xs bg-gray-100 text-gray-700 px-2 py-1 rounded-md"
              >
                #{skill}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="text-center text-xs text-gray-400 py-2 border-t">
        Github Card generated by DevCards
      </div>
    </div>
  );
}